### PR TITLE
WIP - Update links for GCP tiles

### PR DESCRIPTION
**Pull request by tmorrisonsfx**
Jira story: https://signalfuse.atlassian.net/browse/DOCS-1422

Live doc URLs:
- [Cloud Platform](https://docs.signalfx.com/en/latest/integrations/integrations-reference/integrations.google.cloud.platform.html)
- [App Engine](https://docs.signalfx.com/en/latest/integrations/integrations-reference/integrations.google.app.engine.html)
- [BigQuery](https://docs.signalfx.com/en/latest/integrations/integrations-reference/integrations.google.bigquery.html#google-bigquery)
- [Bigtable](https://docs.signalfx.com/en/latest/integrations/integrations-reference/integrations.google.cloud.bigtable.html)
- [Datastore](https://docs.signalfx.com/en/latest/integrations/integrations-reference/integrations.google.cloud.datastore.html)
- [Cloud Functions](https://docs.signalfx.com/en/latest/integrations/integrations-reference/integrations.google.cloud.functions.html)
- [Cloud Pub/Sub](https://docs.signalfx.com/en/latest/integrations/integrations-reference/integrations.google.cloud.pub.sub.html)
- [Cloud Router](https://docs.signalfx.com/en/latest/integrations/integrations-reference/integrations.google.cloud.router.html)
- [Cloud Spanner](https://docs.signalfx.com/en/latest/integrations/integrations-reference/integrations.google.cloud.spanner.html)
- [Cloud Storage](https://docs.signalfx.com/en/latest/integrations/integrations-reference/integrations.google.cloud.storage.html)
- [Compute Engine](https://docs.signalfx.com/en/latest/integrations/integrations-reference/integrations.google.compute.engine.html)
- [Container Engine](https://docs.signalfx.com/en/latest/integrations/integrations-reference/integrations.google.container.engine.html)

Once approved, I will squash and merge the commits.

### CODE REVIEW

**Comment by galpizarsfx** [comment]
Looks good! Both tiles link directly to the documentation site. 
Screen Shot 2020-06-08 at 11 49 36 AM

**Comment by galpizarsfx** [comment]
Screen Shot 2020-06-08 at 11 51 45 AM
Screen Shot 2020-06-08 at 11 51 55 AM
Screen Shot 2020-06-08 at 11 52 05 AM
Screen Shot 2020-06-08 at 11 52 10 AM
Screen Shot 2020-06-08 at 11 52 14 AM

**Comment by galpizarsfx** [comment]
Looks good! Once we create the "Usage" tab, the tiles will look so much cleaner. :)

- All links work
- All tiles have the appropriate "prerequisites" section and corresponding "none" text below, per the content pattern.

**Comment by tmorrisonsfx** [comment]
> Looks good! Once we create the "Usage" tab, the tiles will look so much cleaner. :)
> 
> * All links work
> * All tiles have the appropriate "prerequisites" section and corresponding "none" text below, per the content pattern.

Thanks for the review. Do you need to approve before I can merge?

**Pull request merged**
