### PR TITLE
Updated ReadMe and config files

### PR DESCRIPTION
**Pull request by geoffreyclark**
Work in progress

### CODE REVIEW

**Comment by azimman** [comment]
@geoffreyclark this is looking great. On the "Metrics" section there are two components that we are working to build out. 

1. A machine readable version that can be pulled into the SignalFx app and provide details about each metric individually. These are stored in the `/docs` directory as individual files per metric
1. A human readable version that provides a table with all of the metrics with the format:
 
 | metric name | type | description | default value |
 |--------|--------|--------|------|
 | metric-a  | counter  | counts the number of time _a_ does `foo`  | enabled |

Any help on building out either format would be awesome.  :+1:

**Comment by geoffreyclark** [comment]
I'll start a few from the current files but I probably don't capacity to get to them all. Also the FULL list of stats is around 400....

**Comment by geoffreyclark** [comment]
Ok I think this is ready for a review.

**Comment by azimman** [comment]
@geoffreyclark made a few updates on your [branch](https://github.com/geoffreyclark/integrations/pull/1) ... once you merge those, I'll merge this PR.

**Comment by geoffreyclark** [comment]
Merged those changes in.

**Comment by azimman** [comment]
:+1:

**Pull request merged**
