### PR TITLE
Additional parameters added to vSphere integration

### PR DESCRIPTION
**Pull request by gautam-swaroop**
Parameters have been added for configuration of various timeouts.

### CODE REVIEW

**Comment by molner** [comment]
What's the "MOR" prefix stand for?

**Comment by molner** [comment]
Typo in the "MetricSyncTimeout" line - missing a "T" at the beginning of the description

**Comment by molner** [comment]
Can we provide some specific guidance as to when to increase the value of the "MetricSyncTimeout" and "MORSynctimeout" - and possibly how much to increase it by - other than saying "larger inventories will require a longer timeout"?

Some examples or a description of some sort of linear relationship here between size and timeout values that came as a result of your testing would be ideal.

**Comment by gautam-swaroop** [comment]
@molner 
MOR stands for Managed Object Reference. It could be any object present in the inventory.
eg: folder, datastore, host, vm etc.
Currently, there is no way for us to simulate a larger inventory (It would required high computing machines) where default Timeouts would actually be exceeded. But on customers' side where the inventory's size is large, the default Timeouts provided might exceed. In case of failure due to timeout, when the application is run, the timeout has to be increased.

**Comment by molner** [comment]
Can you change the abbreviation of MOR to be fully spelled out? i.e. the config option of "MORSyncTimeout" would be "ManagedObjectReferenceSyncTimeout". This makes it much more clear. We probably need to spell out somewhere in there also what "Managed Object Reference" is. I don't think most people are going to be familiar with such a definition off the top of their head or whether or not they will need to adjust it off the top of their head.

Maybe I'm missing it, but I also don't see the example sizing/configuration data I requested above. Are you planning on adding that still?

**Comment by gautam-swaroop** [comment]
@molner The sizing/configuration data is not available currently, as there is no way for us to simulate such huge inventory where the default timeouts would exceed. 
OVF has been released with the config option names already. Will change the option "MORSyncTimeout" to "ManagedObjectReferenceSyncTimeout" and similar changes in separate ticket as it would need code change also.

**Comment by molner** [comment]
I'm good

**Pull request merged**
