### PR TITLE
Remove dashboard json files

### PR DESCRIPTION
**Pull request by keitwb**
Our built-in content is publically available in content-discovery and these are
way out of date as we have no mechanism to keep them in sync.

### CODE REVIEW

**Comment by alstory** [comment]
Nothing from me.

**Comment by keitwb** [comment]
@beccatortell do you know of any uses of these dashboard jsons?

**Comment by asuresh4** [comment]
@keitwb - for the docker dashboard group, there's an optional dashboard called Docker Neighbors. It is not part of the default group and I think the instructions actually ask users to import the group from the dashboards directory. Not sure if there's any other such cases and also not sure if we allow v1 dashboard group imports.

**Comment by barbara-sfx** [comment]
I'm clicking Add Your Review but nothing is happening. I have no comments.

**Comment by keitwb** [comment]
@asuresh4 the dashboard at https://github.com/signalfx/integrations/blob/master/collectd-docker/dashboards/Page_Docker.json refuses to import.  Do you know why?

**Pull request merged**
