### PR TITLE
Fix mesos readme format

### PR DESCRIPTION
**Pull request by jrcamp**

### CODE REVIEW

**Comment by molner** [comment]
While you're in here you should probably update "slave" to "agent" to match their change in terminology.

**Comment by jrcamp** [comment]
There's a lot of references to slave including some of the configuration file names. Seems like consistency is better unless we want to go through the trouble of changing everything.

**Comment by molner** [comment]
Consistency is good, but we're already inconsistent in places (e.g. Infrastructure Navigator views for Mesosphere uses "Agent" instead of "Slave"). 

In the interest of time, I'll open a JIRA to track making this consistent in all places (doc, configuration files, dashboards, etc).

**Comment by barbara-sfx** [comment]
@molner Can you add me as a watcher on that Jira? @beccatortell Do you think infra nav will change from agent to slave? I haven't started the mesos doc yet but would like to do it right the first time.

**Comment by beccatortell** [comment]
@barbara-sfx to the extent that the nomenclature changes it will always go from "slave" to "agent", never the reverse.

**Pull request merged**
